name: flutter_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  extra_pedantic: ^4.0.0
  dio: ^5.4.3
  build_runner: ^2.4.11
  json_annotation: ^4.9.0
  flutter_bloc: ^8.1.6
  get_it: ^7.7.0
  bot_toast: ^4.1.3
  extended_image: ^8.2.1
  flutter_svg: ^2.0.10+1
  logger: ^2.4.0


  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
